name: racket-automation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_gregor:
    steps:
      - name: hello gregor
        run: echo "i miss you gregor"
  make_snake:
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
            
      
    
